name: Tests Ejercicio 4 - HTML a Base64

on:
  push:
    paths:
      - 'ex4_html2base64/**'
  pull_request:
    paths:
      - 'ex4_html2base64/**'

jobs:
  test-ex4:
    name: Probar ex4_html2base64
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: '3.11.0'

      - name: Instalar dependencias
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Ejecutar pruebas ex4
        run: |
          python -m pytest ex4_html2base64/tests -v
